import { BorderColor, Height, Margin, Repeat } from "@mui/icons-material";
import { makeStyles } from "@mui/styles";
import { padding } from "@mui/system";

export const useStyles = makeStyles(() => ({
  parent: {
    backgroundColor: "#F5F9F9",
  },
  right: {
    width: "80%",
    marginLeft: "19.5%",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "15px",
  },
  inpBox: {
    position: "relative",
    width: "80%",
  },
  inp: {
    width: "40%",
    padding: "14px",
    background: "transparent",
    border: "1px solid #E3E7E7",
    borderRadius: "5px",
  },
  searchIcon: {
    position: "absolute",
    left: "35%",
    top: "8px",
    width: "20px",
  },
  organization: {
    color: "#4D4D5As",
    display: "inline-block",
    margin: "0 10px",
  },
  inputSectionParent: {
    marginTop: "75px",
    display: "flex",
    alignItems: "center",
  },
  patients: {
    marginLeft: "10px",
  },
  addColor: {
    marginLeft: "8px",
    color: "#679DA8",
  },
  dropDown2: {
    width: "220px",
    height: "56px",
    borderRadius: "4px",
    background: "#fff",
    bborder: "1px solid #C6C9CA",
  },
  dropDown3: {
    boxSizing: "border-box",
    width: "120px",
    height: "56px",
    background: "#FFFFFF",
    border: "1px solid #C6C9CA",
    borderRadius: "4px",
    marginRight: "25px",
  },
  dropDownBox: {
    padding: "10px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dropdown: {
    display: "flex",
    flexDirection: "column",
    width: "18%",
  },
  drop: {
    padding: "15px ",
    borderRadius: "4px",
    display: "inline-block",
    color: "#C8CDCD",
    borderColor: "#C8CDCD",
  },
  inputsParent: {
    width: "65%",
  },
  inputBox: {
    // padding: "0 10px",
    display: "flex",
    // justifyContent: "",
    margin: 0,

    // border: "1px solid red",
  },
  input1: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    width: "100%",
    marginLeft: "14px",
  },
  input2: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    width: "100%",
  },
  textEnabled: {
    background: "#FFF",
    width: "100%",
  },
  inpMiddle: {
    width: "220px",
    boxSizing: "border-box",
    height: "56px",
    background: "#FFFFFF",
    border: "1px solid #C6C9CA",
    borderRadius: "4px",
    left: "0px",
    right: "0px",
    top: "0px",
    "&::placeholder": {
      width: "36px",
      height: "24px",
      fontFamily: "Cairo",
      fontStyle: "normal",
      fontWeight: 400,
      fontSize: "16px",
      lineHeight: "24px",

      color: "#6C7A7A",

      flex: "none",
      order: 0,
      flexGrow: 0,
    },
  },
  drop_down_name: {
    height: "24px",
    fontFamily: "Cairo",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: "16px",
    lineHeight: "24px",
    color: "#6C7A7A",
    display: "inline-block",
    marginBottom: "2px",
  },
  dropDownMiddle: {
    width: "90%",
    padding: "10px",
    outline: "none",
    borderRadius: "3px",
    borderColor: "#C8CDCD",
    color: "gray",
  },
  dropDownMiddle1: {
    width: "90%",
    padding: "10px",
    outline: "none",
    borderRadius: "3px",
    borderColor: "#C8CDCD",
    color: "gray",
    marginTop: "20px",
  },
  textAreaBox: {
    padding: "10px",
    display: "flex",
    alignItems: "center",
  },
  text1: {
    width: "97%",
  },
  text2: {
    display: "flex",

    justifyContent: "space-between",
  },
  textArea: {
    boxSizing: "border-box",
    width: "555px",
    height: "56px",
    background: "#FFFFFF",
    border: "1px solid #C6C9CA",
    borderRadius: "4px",
    paddingTop: "15px",
    paddingRight: "15px",
    "&::placeholder": {
      width: "197px",
      height: "24px",
      fontFamily: "Cairo",
      fontStyle: "normal",
      fontWeight: 400,
      fontSize: "16px",
      lineHeight: "24px",

      color: "#6C7A7A",

      flex: "none",
      order: 0,
      flexGrow: 0,
    },

    resize: "none",
  },
  bottomBox: {
    padding: "10px",
  },
  comapassion: {
    width: "303px",
    height: "25px",
    fontFamily: "Cairo",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "18px",
    lineHeight: "140%",
    color: "#2A3333",
    position: "relative",
    top: "-25px",
    marginLeft: "15px",
  },
  progress1: {
    width: "303px",
    height: "25px",
    fontFamily: "Cairo",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "24px",
    color: "#2A3333",
    position: "relative",
    top: "-35px",
    marginLeft: "15px",
  },
  btnSave: {
    padding: "10px 45px",
    border: "none",
    background: "#C66078",
    borderRadius: "5px",
    color: "#fff",
  },
  para: {
    padding: "4px 10px",
    margin: 0,
    width: "40%",
    background: "#C66078",
    color: "#fff",
    borderRadius: "5px 5px 0 0",
  },
  paraTextArea: {
    resize: "none",
    width: "700px",
    height: "180px",
    borderColor: "#C8CDCD",
    borderRadius: "0 5px 5px 5px",
    outline: "none",
    padding: "10px",
    color: "#6C7A7A",
    fontFamily: "Cairo",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "16px",
    lineHeight: "30px",
  },
  footer: {
    display: "flex",
    alignItems: "center",
    padding: "10px",
  },
  footerPara1: {
    margin: 0,

    fontFamily: "Cairo",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "16px",
    lineHeight: "30px",
  },
  footerPara2: {
    margin: 0,
    marginLeft: "20px",
    fontFamily: "Cairo",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "16px",
    lineHeight: "30px",
    borderBottom: "2px solid #C66078",
    color: "#C66078",
  },
  inpMainBox: {
    display: "flex",
  },
  quesMainBox: {
    width: "40%",
    paddingLeft: "5%",
  },
  quesBox: {
    width: "212px",
    height: "20px",
    fontFamily: "Cairo",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "18px",
    lineHeight: "110%",
  },
  scale_name: {
    width: "134px",

    fontFamily: "Cairo",
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: "18px",
    lineHeight: "140%",

    letterSpacing: "0.1em",

    color: "#387E8D",
    position: "relative",
    left: "23px",
  },
  CircularProgress: {
    position: "relative",
  },
  progressContainer: {
    display: "flex",
  },
  checkbox__container: {
    width: "100%",
    // border: "1px solid blue",
    // marginTop: "20px",
  },
  // checkbox: {
  //   display: "flex",
  //   justifyContent: "space-around",
  // },
  //   border: "1px solid red",
  checkBox: {
    width: "100%",
    // border: "1px solid red",
    display: "flex",
    justifyContent: "space-around",
    position: "relative",
    left: "-20px",
  },
  box1: {
    width: "20px",
    height: "20px",
    marginTop: "20px",
    marginRight: "20px",
    marginLeft: "8px",
    background: "#E7B84F",
    borderRadius: "4px",
  },
  box2: {
    width: "20px",
    height: "20px",
    marginTop: "20px",
    marginRight: "20px",
    marginLeft: "8px",
    background: "#E7B84F",
    borderRadius: "4px",
  },
  box3: {
    width: "20px",
    height: "20px",
    marginTop: "20px",
    marginRight: "20px",
    background: "#FA7344",
    borderRadius: "4px",
  },
  box4: {
    width: "20px",
    height: "20px",
    marginTop: "20px",
    marginRight: "20px",
    marginLeft: "8px",
    background: "#FA7344",
    borderRadius: "4px",
  },
  boxconatiner1: {
    display: "flex",
    alignItem: "center",
  },
  paragraph: {
    display: "flex",
    justifyContent: "space-evenly",
    marginLeft: "-100px",
  },
  bar: {
    border: "1px solid #C6C9CA",
    height: "15px",
    width: "340px",
    borderRadius: "9px",
    marginRight: "20px",
    position: "relative",
    top: "-10px",
  },
  barChild1: {
    width: "170px",
    height: "15px",
    background: "#FA7344",
    borderRadius: "9px",
    position: "relative",
  },
  barChild2: {
    width: "170px",
    height: "15px",
    background: "#E7B84F",
    borderRadius: "9px",
    position: "relative",
  },
  barChild3: {
    height: "15px",
    background: "#49B1A8",
    width: "170px",
    borderRadius: "9px",
    position: "relative",
  },
  progressContainerBar: {
    border: "1px solid lightgrey",
    width: "400px",
    paddingLeft: "20px",
    paddingpRight: "40px",
    height: "180px",
    position: "relative",
    top: "-45px",
    borderRadius: "4px",
    // marginBottom: "0px",
  },
  para_treatment: {
    width: "250px",
    height: "22px",
    fontFamily: "Cairo",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "12px",
    lineHeight: "22px",
    display: "flex",
    alignItems: "center",
    color: "#6C7A7A",
    flex: "none",
    order: 0,
    flexGrow: 0,
  },
  table: {
    border: "1px solid lightgrey",
    width: "100%",
    borderRadius: "5px",
    overflowX: "auto",
  },
  tdHeader: {
    // border: "1px solid red",
    // textAlignF: "center",
    padding: "20px",
    fontFamily: "Cairo",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "14px",
    lineHeight: "2",
    color: "#2A3333",
  },
  actionTD: {
    padding: "15px",
  },
  dateTd: {
    padding: "15px 18px",
    fontFamily: "Cairo",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "24px",
    color: "#2A3333",
  },
  trHead: {
    backgroundColor: "#F5F9F9",
  },
  tr: {
    // border: "1px solid red",
    "&:nth-child(odd)": {
      backgroundColor: "#fff",
    },
  },
  bottomBoxParent: {
    // postion: "relative",
    // top: "-50px",
    padding: "15px",
    display: "flex",
    justifyContent: "space-around",
    // border: "1px solid black",
  },
  para1: {
    margin: 0,
    padding: "8px 0",
    fontFamily: "Cairo",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "16px",
    lineHeight: "30px",
    color: "#2A3333",
  },
  para2: {
    margin: 0,
    padding: "8px 0",
    fontFamily: "Cairo",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "24px",
    color: "#2A3333",
  },
  bottomTextArea: {
    width: "571px",
    height: "220px",
    resize: "none",
    outline: "none",
    border: "1px solid #C6C9CA",
    borderRadius: "4px",
  },
  child1: {
    width: "50%",
  },
  child2: {
    width: "50%",
    marginTop: "45px",
  },
  saveBtnbox: {
    textAlign: "right",
    paddingRight: "50px",
  },
  saveBtn: {
    background: "#C66078",
    padding: "10px 35px",
    border: "none",
    color: "#fff",
    marginBottom: "10px",
    borderRadius: "3px",
    width: "160px",
    height: "50px",
    fontFamily: "Cairo",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "16px",
    lineHeight: "30px",
  },
  messageModal: {
    position: "absolute",
    background: "#FFFFFF",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    border: "0px",
    boxShadow: "0",
    zIndex: "9999",
    width: "907px",
    height: "399px",
    backgroundColor: "#F5F9F9",
  },

  modalContainer: {
    padding: "10px 30px 20px 30px",
    // border: "1px solid red",
    height: "399px",
    width: "907px",
  },
  headerModal: {
    color: "#387E8D",
    fontFamily: "Cairo",
    fontWeight: "800",
    fontSize: "24px",
  },
  treatment_heading: {
    textAlign: "center",
    fontFamily: "Cairo",
    fontStyle: "normal",
    fontWeight: 800,
    fontSize: "24px",
    lineHeight: "110%",
    color: "#508D9B",
  },
  modal_table: {
    width: "100%",
    border: "1px solid lightgrey",
  },
  modal_table_header: {
    padding: "0 10px",
    fontFamily: "Cairo",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "16px",
    lineHeight: "30px",
    color: "#2A3333",
  },
  modal_table_category: {
    padding: "6px 12px",
    // backgroundColor: "#FFFFFF",
    fontFamily: "Cairo",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "16px",
    lineHeight: "30px",
    color: "#2A3333",
  },
  btnContainer: {
    display: "flex",
    alignItems: "flex-end",
  },
  cancelBtn: {
    color: "#C66078",
    borderColor: "#C66078",
    "&:hover": {
      borderColor: "#C66078",
    },
    fontFamily: "Cairo",
    fontWeight: 700,
    fontSize: "16px",
    width: "160px",
    height: "50px",
  },
  label: {
    fontFamily: "Cairo",
    fontWeight: 400,
    fontSize: "16px",
    color: "#6C7A7A",
  },
  label1: {
    fontFamily: "Cairo",
    fontWeight: 400,
    fontSize: "16px",
    color: "#2A3333",
    lineHeight: "24px",
  },
  modal_dropDown: {
    marginLeft: "5px",
  },
}));
